# Generated by Django 4.2.11 on 2026-01-28 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('PRAZO_PROXIMO', 'Prazo proximo'), ('ATRASO', 'Atraso'), ('HUMOR_BAIXO', 'Humor baixo'), ('SEMESTRE_CONCLUIDO', 'Semestre concluido'), ('REPROVACAO', 'Reprovacao')], max_length=30)),
                ('suggestion_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
