# Generated by Django 6.0.1 on 2026-02-02 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PAGO', 'Pago')], default='FREE', max_length=10)),
                ('allow_whatsapp', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=False)),
                ('allow_email', models.BooleanField(default=True)),
                ('consent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
