# Generated by Django 6.0.1 on 2026-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_avatar_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coach_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PAGO', 'Pago (legado)')], default='FREE', max_length=10),
        ),
    ]
