# Generated by Django 6.0.1 on 2026-03-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_coach_enabled_alter_userprofile_plan"),
        ("billing", "0002_institutional_saas_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="billing.institution",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("pt-BR", "Português (Brasil)"), ("en", "English"), ("es", "Español")],
                default="pt-BR",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Aluno"),
                    ("teacher", "Professor"),
                    ("coordinator", "Coordenador"),
                    ("parent", "Responsável"),
                    ("institution_admin", "Admin Institucional"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
