# Generated by Django 6.0.1 on 2026-03-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_institution_role_preferences"),
        ("billing", "0002_institutional_saas_baseline"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enrollment_number", models.CharField(blank=True, max_length=40)),
                ("grade_level", models.CharField(blank=True, max_length=64)),
                ("class_group", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("active", "Ativo"), ("graduated", "Formado"), ("inactive", "Inativo"), ("transferred", "Transferido"), ("suspended", "Suspenso")], default="active", max_length=20)),
                ("account_type", models.CharField(choices=[("institutional", "Institucional"), ("personal", "Pessoal")], default="institutional", max_length=20)),
                ("graduated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="students", to="billing.institution"),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="student_profile", to="accounts.user"),
                ),
            ],
            options={"ordering": ("enrollment_number", "user__name")},
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relationship_type", models.CharField(choices=[("pai", "Pai"), ("mae", "Mãe"), ("responsavel", "Responsável"), ("outro", "Outro")], default="pai", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parent_profiles", to="billing.institution"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parents", to="accounts.user"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="children", to="accounts.user"),
                ),
            ],
            options={"ordering": ("relationship_type",)},
        ),
    ]
