# Generated by Django 6.0.1 on 2026-03-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_student_and_parent_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_profiles", to="accounts.user"),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="student",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parent_links", to="accounts.studentprofile"),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
