# Generated by Django 6.0.1 on 2026-03-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_relationship_adjustments"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentprofile",
            unique_together={("user", "institution")},
        ),
        migrations.AlterUniqueTogether(
            name="parentprofile",
            unique_together={("user", "student", "institution", "relationship_type")},
        ),
    ]
