# Generated by Django 6.0.1 on 2026-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('FINISHED', 'Finalizado')], default='ACTIVE', max_length=20),
        ),
    ]
