# Generated by Django 6.0.1 on 2026-03-12 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="max_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="plan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("razao_social", models.CharField(max_length=255)),
                ("nome_fantasia", models.CharField(blank=True, max_length=255)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("institution_code", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("website_url", models.URLField(blank=True)),
                ("endereco", models.TextField(blank=True)),
                ("cidade", models.CharField(blank=True, max_length=120)),
                ("estado", models.CharField(blank=True, max_length=2)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="institution_logos/")),
                ("ativa", models.BooleanField(default=True)),
                ("is_pilot", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Ativa"), ("suspended", "Suspensa"), ("canceled", "Cancelada"), ("expired", "Expirada")], default="active", max_length=16)),
                ("is_trial", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="billing.institution",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institution_subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={"ordering": ("-start_date", "-id")},
        ),
    ]
