# Generated by Django 6.0.1 on 2026-03-12 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_institutional_saas_baseline"),
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicDisciplineScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score_value", models.PositiveIntegerField()),
                ("classification", models.CharField(max_length=60)),
                ("calculated_at", models.DateTimeField()),
                (
                    "institution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="discipline_scores", to="billing.institution"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="discipline_scores", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ("-calculated_at",)},
        ),
    ]
