# Generated by Django 6.0.1 on 2026-03-12 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_institutional_saas_baseline"),
        ("learning", "0002_academic_discipline_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("achievement_type", models.CharField(choices=[("consistencia_7_dias", "7 dias seguidos estudando"), ("10_tarefas", "10 tarefas concluídas"), ("30_horas_estudo", "30 horas de estudo"), ("score_acima_800", "Score acima de 800")], max_length=40)),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("unlocked_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="achievements", to="billing.institution"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="achievements", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ("-unlocked_at",)},
        ),
        migrations.AlterUniqueTogether(
            name="achievement",
            unique_together={("student", "institution", "achievement_type")},
        ),
    ]
