# Generated by Django 6.0.1 on 2026-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_achievement"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="studytask",
            index=models.Index(fields=["student", "institution", "due_date"], name="learning_task_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(fields=["student", "institution", "created_at"], name="learning_session_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="emotionalcheckin",
            index=models.Index(fields=["student", "institution", "created_at"], name="learning_checkin_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="academicdisciplinescore",
            index=models.Index(fields=["student", "institution", "calculated_at"], name="learning_score_scope_idx"),
        ),
    ]
