# Generated by Django 4.2.11 on 2026-01-28 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_profile', models.BooleanField(default=False)),
                ('has_active_semester', models.BooleanField(default=False)),
                ('has_at_least_one_course', models.BooleanField(default=False)),
                ('has_at_least_one_assessment', models.BooleanField(default=False)),
                ('has_reminder_rule', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
