# Generated by Django 4.2.11 on 2026-01-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_name', models.CharField(blank=True, max_length=255)),
                ('requester_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('INSTITUTION', 'Institution')], max_length=20)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('estimated_users', models.PositiveIntegerField(blank=True, null=True)),
                ('wants_features', models.JSONField(default=list)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('recommended_plan', models.CharField(blank=True, choices=[('LITE', 'Lite'), ('PRO', 'Pro')], max_length=10)),
                ('decided_plan', models.CharField(blank=True, choices=[('LITE', 'Lite'), ('PRO', 'Pro')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AITriageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('input_payload', models.JSONField()),
                ('output_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_logs', to='access_requests.accessrequest')),
            ],
        ),
    ]
