PLAN_LITE = "LITE"
PLAN_PRO = "PRO"
PLAN_CHOICES = [
    (PLAN_LITE, "Lite"),
    (PLAN_PRO, "Pro"),
]

MOOD_VERY_BAD = "VERY_BAD"
MOOD_BAD = "BAD"
MOOD_OK = "OK"
MOOD_GOOD = "GOOD"
MOOD_VERY_GOOD = "VERY_GOOD"
MOOD_CHOICES = [
    (MOOD_VERY_BAD, "Very bad"),
    (MOOD_BAD, "Bad"),
    (MOOD_OK, "Ok"),
    (MOOD_GOOD, "Good"),
    (MOOD_VERY_GOOD, "Very good"),
]

POMODORO_COMPLETED = "COMPLETED"
POMODORO_STOPPED = "STOPPED"
POMODORO_STATUS_CHOICES = [
    (POMODORO_COMPLETED, "Completed"),
    (POMODORO_STOPPED, "Stopped"),
]

TASK_TODO = "TODO"
TASK_DOING = "DOING"
TASK_DONE = "DONE"
TASK_STATUS_CHOICES = [
    (TASK_TODO, "Todo"),
    (TASK_DOING, "Doing"),
    (TASK_DONE, "Done"),
]

EVENT_PROVA = "PROVA"
EVENT_ENTREGA = "ENTREGA"
EVENT_APRESENTACAO = "APRESENTACAO"
EVENT_AULA_IMPORTANTE = "AULA_IMPORTANTE"
EVENT_OUTRO = "OUTRO"
EVENT_TYPE_CHOICES = [
    (EVENT_PROVA, "Prova"),
    (EVENT_ENTREGA, "Entrega"),
    (EVENT_APRESENTACAO, "Apresentacao"),
    (EVENT_AULA_IMPORTANTE, "Aula importante"),
    (EVENT_OUTRO, "Outro"),
]

REMINDER_TARGET_TASK = "TASK"
REMINDER_TARGET_EVENT = "EVENT"
REMINDER_TARGET_CHOICES = [
    (REMINDER_TARGET_TASK, "Task"),
    (REMINDER_TARGET_EVENT, "Event"),
]

CHANNEL_IN_APP = "IN_APP"
CHANNEL_EMAIL = "EMAIL"
CHANNEL_WHATSAPP = "WHATSAPP"
CHANNEL_SMS = "SMS"
CHANNEL_CHOICES = [
    (CHANNEL_IN_APP, "In app"),
    (CHANNEL_EMAIL, "Email"),
    (CHANNEL_WHATSAPP, "WhatsApp"),
    (CHANNEL_SMS, "SMS"),
]

NOTIF_PENDING = "PENDING"
NOTIF_SENT = "SENT"
NOTIF_FAILED = "FAILED"
NOTIFICATION_STATUS_CHOICES = [
    (NOTIF_PENDING, "Pending"),
    (NOTIF_SENT, "Sent"),
    (NOTIF_FAILED, "Failed"),
]

SEMESTER_ACTIVE = "ACTIVE"
SEMESTER_FINISHED = "FINISHED"
SEMESTER_STATUS_CHOICES = [
    (SEMESTER_ACTIVE, "Active"),
    (SEMESTER_FINISHED, "Finished"),
]

COURSE_IN_PROGRESS = "IN_PROGRESS"
COURSE_PASSED = "PASSED"
COURSE_FAILED = "FAILED"
COURSE_STATUS_CHOICES = [
    (COURSE_IN_PROGRESS, "In progress"),
    (COURSE_PASSED, "Passed"),
    (COURSE_FAILED, "Failed"),
]

COACH_PRAZO_PROXIMO = "PRAZO_PROXIMO"
COACH_ATRASO = "ATRASO"
COACH_HUMOR_BAIXO = "HUMOR_BAIXO"
COACH_SEMESTRE_CONCLUIDO = "SEMESTRE_CONCLUIDO"
COACH_REPROVACAO = "REPROVACAO"
COACH_TRIGGER_CHOICES = [
    (COACH_PRAZO_PROXIMO, "Prazo proximo"),
    (COACH_ATRASO, "Atraso"),
    (COACH_HUMOR_BAIXO, "Humor baixo"),
    (COACH_SEMESTRE_CONCLUIDO, "Semestre concluido"),
    (COACH_REPROVACAO, "Reprovacao"),
]

CONTENT_PRE_PROVA = "PRE_PROVA"
CONTENT_ANTI_PROCRASTINACAO = "ANTI_PROCRASTINACAO"
CONTENT_FOCO = "FOCO"
CONTENT_CATEGORY_CHOICES = [
    (CONTENT_PRE_PROVA, "Pre-prova"),
    (CONTENT_ANTI_PROCRASTINACAO, "Anti-procrastinacao"),
    (CONTENT_FOCO, "Foco"),
]

REQUESTER_INDIVIDUAL = "INDIVIDUAL"
REQUESTER_INSTITUTION = "INSTITUTION"
REQUESTER_TYPE_CHOICES = [
    (REQUESTER_INDIVIDUAL, "Individual"),
    (REQUESTER_INSTITUTION, "Institution"),
]

ACCESS_PENDING = "PENDING"
ACCESS_APPROVED = "APPROVED"
ACCESS_REJECTED = "REJECTED"
ACCESS_STATUS_CHOICES = [
    (ACCESS_PENDING, "Pending"),
    (ACCESS_APPROVED, "Approved"),
    (ACCESS_REJECTED, "Rejected"),
]

STEP_1_PROFILE = "STEP_1_PROFILE"
STEP_2_SEMESTER = "STEP_2_SEMESTER"
STEP_3_COURSES = "STEP_3_COURSES"
STEP_4_ASSESSMENTS = "STEP_4_ASSESSMENTS"
STEP_5_REMINDERS = "STEP_5_REMINDERS"
STEP_6_DASHBOARD = "STEP_6_DASHBOARD"

FEATURE_MOOD_BASIC = "MOOD_BASIC"
FEATURE_POMODORO_BASIC = "POMODORO_BASIC"
FEATURE_PLANNER_BASIC = "PLANNER_BASIC"
FEATURE_AGENDA_BASIC = "AGENDA_BASIC"
FEATURE_IN_APP_REMINDERS = "IN_APP_REMINDERS"
FEATURE_DASHBOARD_BASIC = "DASHBOARD_BASIC"
FEATURE_CONTENT_LIMITED = "CONTENT_LIMITED"
FEATURE_EMAIL_NOTIFICATIONS = "EMAIL_NOTIFICATIONS"
FEATURE_REPORTS_ADVANCED = "REPORTS_ADVANCED"
FEATURE_SEMESTER_SUMMARY = "SEMESTER_SUMMARY"
FEATURE_COACH_ADVANCED = "COACH_ADVANCED"
FEATURE_CONTENT_FULL = "CONTENT_FULL"
FEATURE_WHATSAPP = "WHATSAPP"
FEATURE_SMS = "SMS"
