# Generated by Django 6.0.1 on 2026-02-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('PROVA', 'Prova'), ('ENTREGA', 'Entrega'), ('APRESENTACAO', 'Apresentacao'), ('AULA_IMPORTANTE', 'Aula importante'), ('REUNIAO_GRUPO', 'Reuniao em grupo'), ('REUNIAO_PROFESSORES', 'Reuniao com professores'), ('ESTUDAR_FACULDADE', 'Estudar na faculdade'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='target_type',
            field=models.CharField(choices=[('TASK', 'Tarefa'), ('EVENT', 'Evento')], max_length=10),
        ),
    ]
