# Generated by Codex on 2026-02-12

from django.db import migrations


def seed_brain_initial_data(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    GatilhoEmocional = apps.get_model("brain", "GatilhoEmocional")
    RespostaEmocional = apps.get_model("brain", "RespostaEmocional")
    MicroIntervencao = apps.get_model("brain", "MicroIntervencao")

    categorias_data = [
        {
            "nome": "Stress",
            "slug": "stress",
            "emoji": "😮‍💨",
            "gatilhos": [
                "ansioso,ansiedade,nervoso,prova",
                "sobrecarregado,pressao,prazo,estressado",
            ],
            "resposta": "Percebi sinais de stress. Vamos escolher um unico passo simples para comecar agora?",
        },
        {
            "nome": "Duvida",
            "slug": "duvida",
            "emoji": "🤔",
            "gatilhos": [
                "duvida,nao entendi,nao consigo entender",
                "bloqueio,materia dificil,explicacao",
            ],
            "resposta": "Vamos destravar isso por partes. Qual ponto exato da materia esta confuso neste momento?",
        },
        {
            "nome": "Motivacao baixa",
            "slug": "motivacao_baixa",
            "emoji": "🧩",
            "gatilhos": [
                "desmotivado,sem motivacao,desanimado",
                "procrastinando,sem vontade,nada rende",
            ],
            "resposta": "Quando a motivacao cai, o melhor caminho e reduzir o tamanho do passo. Qual tarefa de 10 minutos voce topa iniciar?",
        },
        {
            "nome": "Cansaco mental",
            "slug": "cansaco_mental",
            "emoji": "🫧",
            "gatilhos": [
                "cansado,exausto,sono,dormi pouco",
                "mente cansada,esgotado,sem energia",
            ],
            "resposta": "Seu corpo esta sinalizando cansaco. Que tal recuperar energia com uma pausa breve e depois retomar com uma tarefa leve?",
        },
        {
            "nome": "Foco alto",
            "slug": "foco_alto",
            "emoji": "🎯",
            "gatilhos": [
                "focado,produtivo,concentrado",
                "animado para estudar,ritmo bom,avancando",
            ],
            "resposta": "Excelente momento de foco. Vamos proteger esse ritmo definindo o proximo bloco de estudo sem interrupcoes?",
        },
    ]

    for item in categorias_data:
        categoria, _created = CategoriaEmocional.objects.update_or_create(
            slug=item["slug"],
            defaults={"nome": item["nome"], "emoji": item["emoji"], "ativo": True},
        )

        RespostaEmocional.objects.update_or_create(
            categoria=categoria,
            texto=item["resposta"],
            defaults={"ativo": True},
        )

        for palavras in item["gatilhos"]:
            GatilhoEmocional.objects.update_or_create(
                categoria=categoria,
                palavras_chave=palavras,
                defaults={"ativo": True},
            )

    micro_intervencoes_data = [
        {"nome": "Beber agua", "texto": "Pare 1 minuto e beba um copo de agua para hidratar e retomar com clareza."},
        {
            "nome": "Respiracao 4-4-4",
            "texto": "Inspire por 4 segundos, segure por 4 segundos e expire por 4 segundos durante 3 ciclos.",
        },
    ]
    for item in micro_intervencoes_data:
        MicroIntervencao.objects.update_or_create(
            nome=item["nome"],
            defaults={"texto": item["texto"], "ativo": True},
        )


def unseed_brain_initial_data(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    MicroIntervencao = apps.get_model("brain", "MicroIntervencao")

    CategoriaEmocional.objects.filter(
        slug__in=["stress", "duvida", "motivacao_baixa", "cansaco_mental", "foco_alto"]
    ).delete()
    MicroIntervencao.objects.filter(nome__in=["Beber agua", "Respiracao 4-4-4"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("brain", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_brain_initial_data, unseed_brain_initial_data),
    ]
