# Generated by Codex on 2026-02-12

from django.db import migrations


def seed_social_category(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    GatilhoEmocional = apps.get_model("brain", "GatilhoEmocional")
    RespostaEmocional = apps.get_model("brain", "RespostaEmocional")

    categoria_social, _created = CategoriaEmocional.objects.update_or_create(
        slug="social",
        defaults={"nome": "Social", "emoji": "🙌", "ativo": True},
    )

    gatilhos = [
        "obrigado",
        "obrigada",
        "valeu",
        "gratidão",
        "agradecido",
    ]
    for gatilho in gatilhos:
        GatilhoEmocional.objects.update_or_create(
            categoria=categoria_social,
            palavras_chave=gatilho,
            defaults={"ativo": True},
        )

    respostas = [
        "Fico feliz em ajudar 😊",
        "Sempre que precisar, estou aqui.",
        "Conta comigo para o que precisar.",
        "É muito bom saber que estou ajudando.",
    ]
    for texto in respostas:
        RespostaEmocional.objects.update_or_create(
            categoria=categoria_social,
            texto=texto,
            defaults={"ativo": True},
        )


def unseed_social_category(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    CategoriaEmocional.objects.filter(slug="social").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("brain", "0002_seed_initial_data"),
    ]

    operations = [
        migrations.RunPython(seed_social_category, unseed_social_category),
    ]
