# Generated by Codex on 2026-02-12

from django.db import migrations


CATEGORY_RESPONSES = {
    "stress": [
        "Entendi. Vamos reduzir isso: qual e a menor parte que voce consegue fazer agora?",
        "Respira um pouco. O que esta te pressionando mais hoje?",
        "Se parecer demais, a gente escolhe so 1 prioridade para hoje.",
        "Vamos com calma: 10 minutos agora ja contam como progresso.",
    ],
    "duvida": [
        "Tudo bem ter duvida. Qual parte ficou mais confusa?",
        "Me diga o tema e eu organizo em passos simples.",
        "O que voce entendeu ate aqui? Mesmo que seja pouco.",
        "Quer um exemplo pratico para destravar esse conteudo?",
    ],
    "motivacao_baixa": [
        "Vamos so comecar: 15 minutos e pronto. Depois voce decide se continua.",
        "Escolhe uma tarefa pequena. O objetivo e ritmo, nao perfeicao.",
        "Quer que eu te ajude a escolher a tarefa mais facil para destravar?",
        "Voce nao precisa render tudo hoje. So precisa dar o primeiro passo.",
    ],
    "cansaco_mental": [
        "Parece cansaco mental. Que tal uma pausa curta antes de continuar?",
        "Vamos reduzir a carga: escolha algo leve e rapido agora.",
        "Se estiver pesado, da para dividir a tarefa em duas partes menores.",
        "Me diz como voce esta agora de 0 a 10, so para eu ajustar melhor.",
    ],
    "foco_alto": [
        "Otimo! Quer aproveitar e atacar a tarefa mais dificil agora?",
        "Perfeito. Qual e a prioridade #1 para concluir hoje?",
        "Se o foco esta alto, da para adiantar uma etapa e ganhar folga depois.",
        "Bora transformar esse foco em resultado: qual meta para a proxima 1 hora?",
    ],
}


def seed_expand_category_replies(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    RespostaEmocional = apps.get_model("brain", "RespostaEmocional")

    for slug, responses in CATEGORY_RESPONSES.items():
        categoria = CategoriaEmocional.objects.filter(slug=slug).first()
        if not categoria:
            continue

        for text in responses:
            RespostaEmocional.objects.update_or_create(
                categoria=categoria,
                texto=text,
                defaults={"ativo": True},
            )


def unseed_expand_category_replies(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    RespostaEmocional = apps.get_model("brain", "RespostaEmocional")

    for slug, responses in CATEGORY_RESPONSES.items():
        categoria = CategoriaEmocional.objects.filter(slug=slug).first()
        if not categoria:
            continue
        RespostaEmocional.objects.filter(categoria=categoria, texto__in=responses).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("brain", "0003_seed_social_category"),
    ]

    operations = [
        migrations.RunPython(seed_expand_category_replies, unseed_expand_category_replies),
    ]
