# Generated by Codex on 2026-02-12

from django.db import migrations


def seed_evolucao_category(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    GatilhoEmocional = apps.get_model("brain", "GatilhoEmocional")
    RespostaEmocional = apps.get_model("brain", "RespostaEmocional")

    categoria_evolucao, _created = CategoriaEmocional.objects.update_or_create(
        slug="evolucao",
        defaults={"nome": "Evolução", "emoji": "📈", "ativo": True},
    )

    gatilhos = [
        "estou melhor",
        "evolui",
        "evoluí",
        "melhorei",
        "to indo bem",
        "tô indo bem",
        "deu certo",
        "consegui",
        "bati a meta",
        "terminei",
        "orgulhoso",
        "orgulhosa",
    ]
    for palavras_chave in gatilhos:
        GatilhoEmocional.objects.update_or_create(
            categoria=categoria_evolucao,
            palavras_chave=palavras_chave,
            defaults={"ativo": True},
        )

    respostas = [
        "Que boa notícia. Quer me dizer o que você fez que ajudou a melhorar?",
        "Parabéns! Qual foi a parte mais difícil que você superou?",
        "Isso é progresso real. Quer definir a próxima meta pequena para manter o ritmo?",
        "Muito bom. Quer registrar essa vitória para lembrar nos dias difíceis?",
    ]
    for texto in respostas:
        RespostaEmocional.objects.update_or_create(
            categoria=categoria_evolucao,
            texto=texto,
            defaults={"ativo": True},
        )


def unseed_evolucao_category(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    CategoriaEmocional.objects.filter(slug="evolucao").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("brain", "0004_expand_respostas_categorias"),
    ]

    operations = [
        migrations.RunPython(seed_evolucao_category, unseed_evolucao_category),
    ]
