# Generated by Codex on 2026-02-12

from django.db import migrations


def seed_evolucao_slang_triggers(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    GatilhoEmocional = apps.get_model("brain", "GatilhoEmocional")

    categoria = CategoriaEmocional.objects.filter(slug="evolucao").first()
    if not categoria:
        return

    girias = [
        "que massa",
        "show",
        "top",
        "consegui",
    ]
    for palavras_chave in girias:
        GatilhoEmocional.objects.update_or_create(
            categoria=categoria,
            palavras_chave=palavras_chave,
            defaults={"ativo": True},
        )


def unseed_evolucao_slang_triggers(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    GatilhoEmocional = apps.get_model("brain", "GatilhoEmocional")

    categoria = CategoriaEmocional.objects.filter(slug="evolucao").first()
    if not categoria:
        return

    GatilhoEmocional.objects.filter(
        categoria=categoria,
        palavras_chave__in=["que massa", "show", "top", "consegui"],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("brain", "0005_seed_evolucao_category"),
    ]

    operations = [
        migrations.RunPython(seed_evolucao_slang_triggers, unseed_evolucao_slang_triggers),
    ]
