# Generated by Codex on 2026-02-12

from django.db import migrations


def seed_evolucao_maravilha_trigger(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    GatilhoEmocional = apps.get_model("brain", "GatilhoEmocional")

    categoria = CategoriaEmocional.objects.filter(slug="evolucao").first()
    if not categoria:
        return

    GatilhoEmocional.objects.update_or_create(
        categoria=categoria,
        palavras_chave="maravilha",
        defaults={"ativo": True},
    )


def unseed_evolucao_maravilha_trigger(apps, schema_editor):
    CategoriaEmocional = apps.get_model("brain", "CategoriaEmocional")
    GatilhoEmocional = apps.get_model("brain", "GatilhoEmocional")

    categoria = CategoriaEmocional.objects.filter(slug="evolucao").first()
    if not categoria:
        return

    GatilhoEmocional.objects.filter(categoria=categoria, palavras_chave="maravilha").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("brain", "0006_expand_evolucao_girias"),
    ]

    operations = [
        migrations.RunPython(seed_evolucao_maravilha_trigger, unseed_evolucao_maravilha_trigger),
    ]
