# Generated by Django 6.0.1 on 2026-02-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brain", "0007_expand_evolucao_giria_maravilha"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatPendingAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pending_action", models.CharField(max_length=40)),
                ("step", models.PositiveSmallIntegerField(default=1)),
                ("draft_title", models.CharField(blank=True, max_length=200)),
                ("draft_description", models.TextField(blank=True)),
                ("draft_due_date", models.DateField(blank=True, null=True)),
                ("draft_due_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brain_pending_action",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
