# Generated by Django 6.0.1 on 2026-02-23 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0008_chatpendingaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCoachingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_reference', models.DateField(help_text='Segunda-feira da semana avaliada')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('STABLE', 'Stable'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='STABLE', max_length=10)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_coaching_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week_reference', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('user', 'week_reference'), name='uniq_weekly_coaching_user_week')],
            },
        ),
    ]
