# Generated by Django 6.0.1 on 2026-02-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationqueue',
            name='action_taken',
            field=models.CharField(choices=[('NONE', 'None'), ('CONFIRMED', 'Confirmed'), ('DELAYED', 'Delayed'), ('CANCELED', 'Canceled')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='to_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='channel',
            field=models.CharField(choices=[('IN_APP', 'In app'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=20),
        ),
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_from', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField()),
                ('parsed_action', models.CharField(choices=[('NONE', 'None'), ('CONFIRMED', 'Confirmed'), ('DELAYED', 'Delayed'), ('CANCELED', 'Canceled')], default='NONE', max_length=20)),
                ('matched_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_messages', to='notifications.notificationqueue')),
            ],
        ),
    ]
