# Generated by Django 6.0.1 on 2026-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_inappnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('FAILED', 'Erro')], default='PENDING', max_length=20),
        ),
    ]
